CREATE TABLE IF NOT EXISTS Chief (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Worker (
	id SERIAL PRIMARY KEY,
	chief_id INTEGER NOT NULL REFERENCES Chief(id),
	name VARCHAR(60) NOT NULL,
    department VARCHAR(60) NOT NULL
);